# llvm-mingw 交叉编译工具链文件。
# 用法：cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-llvm-mingw.cmake -DWINVER_ARCH=x86|x64|arm64
set(CMAKE_SYSTEM_NAME Windows)

if(NOT DEFINED WINVER_ARCH)
    set(WINVER_ARCH "x64")
endif()

if(WINVER_ARCH STREQUAL "x86")
    set(WINVER_TRIPLE i686-w64-mingw32)
    set(CMAKE_SYSTEM_PROCESSOR x86)
elseif(WINVER_ARCH STREQUAL "x64")
    set(WINVER_TRIPLE x86_64-w64-mingw32)
    set(CMAKE_SYSTEM_PROCESSOR AMD64)
elseif(WINVER_ARCH STREQUAL "arm64")
    set(WINVER_TRIPLE aarch64-w64-mingw32)
    set(CMAKE_SYSTEM_PROCESSOR ARM64)
else()
    message(FATAL_ERROR "Unknown WINVER_ARCH: ${WINVER_ARCH} (expected x86|x64|arm64)")
endif()

set(CMAKE_C_COMPILER   ${WINVER_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${WINVER_TRIPLE}-g++)
set(CMAKE_RC_COMPILER  ${WINVER_TRIPLE}-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
